SET LINESIZE 300;
SET PAGESIZE 1000;
COLUMN cust_id format 'A7';
COLUMN cust_gender FORMAT 'A11';
COLUMN member_status FORMAT 'A13';
COLUMN pro_id format 'A6';
COLUMN pro_uom format 'A7';
UPDATE product SET pro_desc = '-' WHERE pro_desc is null;
COLUMN apt_code format 'A8';
COLUMN apt_starttime format 'A13';
COLUMN apt_endtime format 'A11';
COLUMN outlet_id format 'A9';
COLUMN outlet_phone format 'A12';
COLUMN staff_id format 'A8';
COLUMN staff_birth format 'A11';
COLUMN staff_gender format 'A12';
COLUMN service_id format 'A10';
COLUMN payment_id format 'A10';
COLUMN proservice_id format 'A13';
COLUMN aptdetails_id format 'A13';
COLUMN total_price format 9999;
